### PR TITLE
upgrade package version and move vm to quay.io

### PR DESCRIPTION
**Pull request by grugna**
Description about what this pull request does.

Please make sure to follow the [DEV guidelines](https://gen3.org/resources/developer/dev-introduction/) before asking for review.

### New Features

- Implemented XXX

### CODE REVIEW

**Review by bobaekang — COMMENTED** [review]
I was able to successfully bring up the local docker compose stack with a locally built image for portal.

However, I'm noticing some slight changes in style, the most notable of which is CSS for font-family, leading to overwriting Source Sans Pro with some default font. I'll dig more into this and report back here.

**Comment by grugna** [comment]
@bobaekang that is probably from the new "@gen3/ui-component": "^0.6.2".

**Comment by bobaekang** [comment]
> @bobaekang that is probably from the new "@gen3/ui-component": "^0.6.2".

@grugna You're right. And I think I found where the change of style comes from: importing stylesheet from a new dependency `antd` from a component: https://github.com/uc-cdis/gen3-ui-component/blob/acd77c857bd277886a9c76cd08ea7f724a1b12f6/src/components/filters/FilterSection/index.jsx#L6. That is, styles defined here (`antd/dist/antd.css`) is overwriting those from the UI component library due to the import order.

I have many thoughts about this change, including that this is unnecessarily adding too much weight to the application by importing a comprehensive stylesheet _knowing_ that Gen3 portal won't be using most of the provide CSS classes...  To remedy this, here we can either:

1. contribute to `uc-cdis/gen3-ui-component`
2. bite the bullet and fork `uc-cdis/gen3-ui-component`
3. build our own ui components from scratch

Regardless, simply sticking to the previous version (0.6.1) is not an option if we want to take advantage of the new and/or filter feature.

**Comment by grugna** [comment]
@bobaekang can you add a ticket in Jira to discuss about how to move forward with the ui component? For the time being I am just going to remove that line from this PR in order to keep it moving.

**Comment by bobaekang** [comment]
@grugna Will do. Just to be clear, UI for the new and/or filter feature is not available with ui-components 0.6.1.

**Comment by grugna** [comment]
what do you mean with `new and/or filter feature`?

**Comment by bobaekang** [comment]
@grugna You can refer to [this PR for `gen3-ui-component`](https://github.com/uc-cdis/gen3-ui-component/pull/77) and [this PR for `guppy`](https://github.com/uc-cdis/guppy/pull/98). The point is, they both need to be updated to the respective versions for this feature to work.

**Comment by grugna** [comment]
@bobaekang I ll consider those item as part of the ticket you created. I ll close this since it is just a node update.

**Pull request merged**
